### ISSUE TITLE
Question on LocalVectorStore embeddings.

### ISSUE THREAD

**Issue by deckarep** [go-aie/gptbot#1]
Hello,

I'm trying to wrap my head around the Local Vector Store. What I know is that it's primarily used for small-scale docs and it has the ability to load up from disk in JSON format.

But, it seems to lack the ability to create a store and serialize "save" to disk in JSON format right?

Doesn't it make sense to persist embeddings across runs of the application so that you don't have to recreate them each time? 

If you think this makes sense I could probably help contribute this ability and write the code to do that.

Thanks,

-deckarep

**Comment by RussellLuo** [comment]
Hi @deckarep, thanks for your attention!

Yes, I agree that the current implementation of the Local Vector Store is incomplete. Your proposal sounds great, and PR is welcome :)

**Comment by deckarep** [comment]
@RussellLuo - thanks for the quick response see the associated Pull Request: https://github.com/go-aie/gptbot/pull/2

**Comment by RussellLuo** [comment]
Fixed by #2.
